excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - library/
disabled_rules:
  - opening_brace
  - statement_position
  - variable_name_min_length
line_length: 110
type_body_length:
  - 300 # warning
  - 400 # error
variable_name_max_length:
  - 40 # warning
  - 60 # error
variable_name_min_length:
  - 3 # warning
  - 2 # error
